const DEFAULT_ADDRESS = "https://localhost:44346/api/Inventory/";
const ADDRESS = Object.freeze({
  PAGING: DEFAULT_ADDRESS + "paging?",
  INSERT: DEFAULT_ADDRESS,
  MAXCODE: DEFAULT_ADDRESS + "MaxCode/",
  GET_BY_SKUCODE: DEFAULT_ADDRESS + "SKUCode/",
  GET_BY_ID: DEFAULT_ADDRESS,
  DEFAULT_ADDRESS: DEFAULT_ADDRESS,
  DELETE: DEFAULT_ADDRESS + "byId/",
  DELETE_MULTIPLE: DEFAULT_ADDRESS + "multiple",
  GET_BY_PARENT_ID: DEFAULT_ADDRESS + "ParentId/",
  INSERT_INVENTORY_DETAIL: DEFAULT_ADDRESS + "detail/",
});

export default ADDRESS